name: GitHub Actions Verification
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - main
      - master
jobs:
  Lint-and-Security-Check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # Utilisation de conteneurs Docker pour ESLint et Stylelint pourrait être une option, mais ici,
      # nous supposons l'utilisation de Node.js via GitHub Actions pour une intégration directe.
      
      - name: Set up Node.js (Requis pour ESLint et Stylelint)
        uses: actions/setup-node@v3
        with:
          node-version: '14' # Choisissez une version de Node.js compatible avec vos outils
      
      - name: Install ESLint (Supposant que vous avez un .eslintrc dans votre repo)
        run: |
          npm init -y
          npm install eslint --save-dev
          
      - name: Run JavaScript Linter (ESLint)
        run: npx eslint .
      
    #   - name: Install Stylelint (Supposant que vous avez un .stylelintrc dans votre repo)
    #     run: |
    #       npm install stylelint stylelint-config-standard --save-dev
          
    #   - name: Run CSS Linter (Stylelint)
    #     run: npx stylelint "**/*.css"

      - name: Echo branch and repository info
        run: |
          echo "Branch Name: ${{ github.ref }}"
          echo "Repository: ${{ github.repository }}"

      - name: List files in the repository
        run: |
          ls -lah

      - name: Success message
        run: echo "All checks passed successfully!"
